spring:
  application:
    name: HOPS_NEW_API
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://192.168.3.16:13306/HOPS
    username: hops
    password: kmi@124578
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
server:
  port: 28080
  error:
    include-stacktrace: never
logging:
  level:
    root: INFO
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}][%-5level][%-15thread][%-30.30logger{0}] %msg%n"
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%-5level][%-15thread][%-30.30logger{0}] %msg%n"
  file:
    name: logs/catalina.out
#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: false

