spring:
  active : edu
  application:
    name: HOPS_NEW_API
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://db-een48.vpc-cdb.ntruss.com:3306/EDU
    username: vb_dev
    password: kmi@1324
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 28080
  error:
    include-stacktrace: never
logging:
  level:
    root: INFO
    org.mybatis: DEBUG
    org.apache.mybatis: DEBUG
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}][%-5level][%-15thread][%-30.30logger{0}] %msg%n"
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%-5level][%-15thread][%-30.30logger{0}] %msg%n"
  file:
    name: logs/catalina.out
#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: false
  #Redis
  redis:
    host: "localhost" # Redis 서버 호스트
    port: 6379      # Redis 서버 포트
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 0
        max-wait: 1000 # 커넥션 풀에서 연결을 얻기 위해 기다리는 최대 시간 (ms)
        timeout: 3000         # Redis 명령어의 응답 대기 시간 (ms)
        connect-timeout: 5000 # Redis 서버에 연결하는 데 걸리는 최대 시간 (ms)

