spring:
  application:
    name: VITA_BACK
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://192.168.3.16:13306/HOPS
    username: hops
    password: kmi@124578
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false
  mail:
    host: smtp.naver.com
    port: 587
    username: moonja89
    password: 78ZVSLSW9VMV
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
server:
  port: 28080
  error:
    include-stacktrace: never
logging:
  level:
    root: INFO
    com.vita.back.common.aspect.LogAspect: INFO
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}][%-5level][%-15thread][%-30.30logger{0}] %msg%n"
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%-5level][%-15thread][%-30.30logger{0}] %msg%n"
  file:
    name: logs/catalina.out
#p6spy 설정
decorator:
  datasource:
    p6spy:
      enable-logging: false
#Redis
redis:
  host: "localhost" # Redis 서버 호스트
  port: 6379      # Redis 서버 포트
  lettuce:
    pool:
      max-active: 10
      max-idle: 8
      min-idle: 0
      max-wait: 1000 # 커넥션 풀에서 연결을 얻기 위해 기다리는 최대 시간 (ms)
      timeout: 3000         # Redis 명령어의 응답 대기 시간 (ms)
      connect-timeout: 5000 # Redis 서버에 연결하는 데 걸리는 최대 시간 (ms)
#jwt
jwt:
  secret: "OMNICARE_VITA"
  expiration: 3600 # 1시간 (초 단위)
  refresh-expiration: 86400 # 1일